### ISSUE TITLE
How the .ts file would converted to .js

### ISSUE THREAD

**Issue by dipti-code** [jpolley/WebdriverIO_v5_TypeScript#5]
After looking into the code, some of my questions are 
1-->where is the output folder mentioned in tsconfig.json after conversion to js.
2-->do we not required tsc command before executing.
3-->are we going to run .ts files not .js files?

**Comment by jpolley** [comment]
Howdy 👋,

1. You don't need an output folder 
2. You don't have to use `tsc` 
3. You are going to tun .ts files 

This is possible because of `ts-node`. 

WebdriverIO TypeScript setup here: https://webdriver.io/docs/typescript.html 
ts-node repo here: https://github.com/TypeStrong/ts-node

**Comment by dipti-code** [comment]
@jpolley HiJeremy, am new to creating a framework with appium and webdriverIO with typescript.
So earlier from my knowledge i know first you have to create the .ts file and in the tsconfig.json mentioned the output as well as in package.json run tsc then other script.
But since you are mentioning  no tsc command is required, then how it compile and run m y ts projects for Es2015 compatible and  also if in my framework any one of the file extension is .js should it create  problem.


Kindly help me from the scratch.
1-->I started with npm init.
2--> then ????
3-->tsconfig.json what should enable ?
4-->and in package.json what should be version , and in exclude folder?

Please guide. and also in future i may need your help for any problem solving on typescript.

**Comment by jpolley** [comment]
@dipti-code I haven't used WebdriverIO with Appium yet so I can't really help out with that. Running these commands should help you get started with this project though: 
```
git clone git@github.com:jpolley/WebdriverIO_v5_TypeScript.git
cd WebdriverIO_v5_TypeScript
npm install
npm test
```
